name = "custom-router-web-test"
main = ".open-next/worker.js"
compatibility_date = "2026-02-18"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "ROUTER_DB"
database_name = "custom-router-test"
database_id = "6673823f-8832-4a64-8be8-748f8363e3bc"

[[kv_namespaces]]
binding = "ROUTER_KV"
id = "7f6496dd57a8432a9a634d08b3f0ae01"

[vars]
ROUTER_NAME = "custom-router"
