name = "custom-router-ingest-worker"
main = "src/index.ts"
compatibility_date = "2026-02-18"

[triggers]
crons = ["0 4 * * *"]

[[d1_databases]]
binding = "ROUTER_DB"
database_name = "replace-with-your-d1-database-name"
database_id = "00000000-0000-0000-0000-000000000000"

[[kv_namespaces]]
binding = "ROUTER_KV"
id = "00000000000000000000000000000000"

[vars]
ROUTER_NAME = "custom-router"
